/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package gradle.logger.helper.plugin

import org.gradle.api.Project
import org.gradle.api.Plugin
import org.gradle.api.plugins.JavaPlugin
import org.gradle.jvm.tasks.Jar

/**
 * A simple 'hello world' plugin.
 */
class GradleLoggerHelperPlugin : Plugin<Project> {
    override fun apply(project: Project) {
        // Register a task
//        val x: Class<JavaPlugin> = typeOf<JavaPlugin>().javaClass
        project.plugins.withType(JavaPlugin::class.java) { jp: JavaPlugin -> }
        project.dependencies
        project.tasks.withType(Jar::class.java) {jar -> }
        project.tasks.register("greeting") { task ->
            task.doLast {
                println("Hello from plugin 'gradle.logger.helper.plugin.greeting' - aaaaa")
                println("why doesnt this work")
            }

        }

    }
}
