/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package gradle.logger.helper.plugin

import org.gradle.internal.impldep.org.junit.Ignore
import org.gradle.testfixtures.ProjectBuilder
import kotlin.test.Test
import kotlin.test.assertNotNull

/**
 * A simple unit test for the 'gradle.logger.helper.plugin.greeting' plugin.
 */
class GradleLoggerHelperPluginTest {

    @Ignore
    @Test fun `plugin registers task`() {
        // Create a test project and apply the plugin
        val project = ProjectBuilder.builder().build()
        project.plugins.apply("gradle.logger.helper.plugin.greeting")

        // Verify the result
        assertNotNull(project.tasks.findByName("greeting"))
    }
}
